# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fb8c02de1ae0f3077ec451730c42076453cd0c76a1289c1513ba09f7df3353d977035bb18559efad8f66b89a50358848595cdea7c51337ae70cd2bb0aab36f

test:
  secret_key_base: 89b5c3e58cb1683f31a69de83b8b3d4bbae3b7105d715b8ae358307f1fcad08caa8f7d165ba6a1e7589b1dda6c14befa0176008bf40ecfeb32324193ffb7fd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
